name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    permissions:
      contents: write
      pull-requests: write

    uses: GlueOps/renovatebot/.github/workflows/bump-version.yaml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
