name: Cleanup Images

on: [push]

jobs:
  delete-untagged-images:
    name: Cleanup Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
